language: swift
osx_image: xcode12.5.1
branches:
  only:
    - xcuitest_poc

before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
  - fastlane scan -scheme JellyfinPlayer --device "iPhone 12 Pro Max"
