name: "Build 🔨"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ""
    strategy:
      matrix:
        scheme:
          - "JellyfinPlayer"
          - "JellyfinPlayer tvOS"
          
    runs-on: macos-11
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
    
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: actions/cache@v2
        id: cocoapods-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Install pods
        run: pod install
      
      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.scheme }}-spm2-
            
      - name: Cache DerivedData folder
        uses: actions/cache@v2
        with:
          path: "~/Library/Developer/Xcode/DerivedData"
          key: ${{ runner.os }}-${{ matrix.scheme }}-deriveddata        
          
      - name: testing ... iPhone 12 Pro Max
        run: xcodebuild build-for-testing -scheme JellyfinPlayer -workspace JellyfinPlayer.xcworkspace -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12 Pro Max' clean build test CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
        
